### ISSUE TITLE
Add /room/:room_id/transcript/message/:message_id endpoint

### ISSUE THREAD

**Issue by laserlemon** [collectiveidea/fireside#16]
This endpoint should render the same response as the other transcript endpoints, but for the day that contains the specified message.

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Additionally, since you have lots of issues open, you'll only get this issue once, but we'll close everything. Thanks!
